my_dbt_project:
  outputs:
    dev:
      type: duckdb
      path: /opt/airflow/data/Silver/dev.duckdb
      threads: 1

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
